name: publish

on:
  release:
    types:
      - created
  workflow_dispatch:


jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python "3.6"
      uses: actions/setup-python@v2
      with:
        python-version: "3.6"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f global_chem_package/requirements.txt ]; then pip install -r global_chem_package/requirements.txt; fi
        pip install global_chem_package/
    - name: Build a binary wheel and a source tarball
      run: |
        pip install build
        python -m build --sdist --wheel --outdir global_chem_package/dist/ .
    - name: Publish distribution 📦 to PyPI
      uses: pypa/gh-action-pypi-publish@master
      with:
        password: ${{ secrets.PYPI_API_TOKEN }}
