name: Speed Test GlobalChem Website

on:
  schedule:
    - cron: '0 0 * * *'
    
jobs:
  test:
    runs-on: "ubuntu-latest"

steps:
  - name: Running Page Speed Insights
    uses: jakepartusch/psi-action@v1.2
    id: psi
    with:
      url: "https://www.globalchemistry.org"
      threshold: 70
      strategy: mobile
